//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hisss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hisss.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error reported, operation succeded.
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization in progress. Try again after the device becomes ready..
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuse for Endorser or Imprinter is blown.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertical line on the Carrier
        ///Sheet not sensed. If error persists contact ricoh support.
        /// </summary>
        public static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The horizontal line on the Carrier
        ///Sheet not sensed, If error persists contact ricoh support.
        /// </summary>
        public static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The material you scanned is not a Carrier
        ///Sheet. Load the Carrier Sheet again, and
        ///then retry..
        /// </summary>
        public static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal device drive system, The carrier unit may be locked or the part should be replaced..
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal light level.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal target error, cannot control SPC.
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorser / Imprinter error.
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command, An illegal process in the driver or control, or an unknown device failure..
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown code in the CDB field.
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported logical unit. An illegal process in the driver or control, or an unknown device failure. Restart computer and scanner and try again.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified read area is not
        ///suitable for the document size when
        ///the AutoBorderDetection function
        ///and Read Area Specification
        ///function are combined.
        ///Or the document detection sensor
        ///error occurs..
        /// </summary>
        public static string _17104896 {
            get {
                return ResourceManager.GetString("17104896", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter field, restart computer and scanner and try again.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window ID combination error, restart computer and scanner and try again.
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special document or patch code document was detected..
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence error, restart computer and scanner and try again.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified data source (Image Processing
        ///Software Option) does not support the
        ///Carrier Sheet..
        /// </summary>
        public static string _2000 {
            get {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is being reset.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image transfer error, reduce scan image size and try again.
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCSI parity error, (SCSI card, SCSI
        ///cable, etc.).
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source manager load error, is TWAIN installed?.
        /// </summary>
        public static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source manager load error, is TWAIN installed?.
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source open error, device may not be on, twain may not be installed, or scanner in use by another app.
        /// </summary>
        public static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source enable error, scanner may be busy or cover is on.
        /// </summary>
        public static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the connected device.
        /// </summary>
        public static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A paper jam has occurred.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer mode is not supported.
        /// </summary>
        public static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not supported.
        /// </summary>
        public static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a file, check path.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal initialization for Java is not called.
        ///Call internal initialization for Java..
        /// </summary>
        public static string _33554433 {
            get {
                return ResourceManager.GetString("33554433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Java SDK environmental error occurred. Check if the SDK is installed properly.
        /// </summary>
        public static string _33554434 {
            get {
                return ResourceManager.GetString("33554434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method is being executed in another
        ///form. Try again after the current execution of
        ///the method has completed..
        /// </summary>
        public static string _33554435 {
            get {
                return ResourceManager.GetString("33554435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Image Processing Software Option is not
        ///installed. Install the IPSO.
        /// </summary>
        public static string _33554436 {
            get {
                return ResourceManager.GetString("33554436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire the total
        ///number/names/numbers of templates in the
        ///Image Processing Software Option. Check if
        ///the Image Processing Software Option is
        ///installed properly..
        /// </summary>
        public static string _33554437 {
            get {
                return ResourceManager.GetString("33554437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source does not support the
        ///configuration screen only mode.
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window handle of the application is
        ///invalid.
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source in use does not
        ///support the DeviceOnline function.
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF is not supported by this scanner.
        /// </summary>
        public static string _37 {
            get {
                return ResourceManager.GetString("37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatbed (FB) is not supported by this scanner.
        /// </summary>
        public static string _38 {
            get {
                return ResourceManager.GetString("38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper feed error, or all the
        ///document pages were determined
        ///to be blank. Or user canceled on retry..
        /// </summary>
        public static string _39 {
            get {
                return ResourceManager.GetString("39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF cover, or endorser / imprinter cover is open.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper eject error (or the ClearPage
        ///function is not supported).
        /// </summary>
        public static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT FAMILY is not
        ///&quot;FUJITSU&quot; or “PaperStream IP”.
        /// </summary>
        public static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled by the user, or detected
        ///an error which causes the device to
        ///be unable to continue scanning. insufficient disk space, pattern file error,
        ///insufficient memory, image transfer error,
        ///etc..
        /// </summary>
        public static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is in use by another
        ///application.
        /// </summary>
        public static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory, reduce image scan size.
        /// </summary>
        public static string _44 {
            get {
                return ResourceManager.GetString("44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient disk space, or file
        ///writing error.
        /// </summary>
        public static string _45 {
            get {
                return ResourceManager.GetString("45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to path denied or save file is in use.
        /// </summary>
        public static string _46 {
            get {
                return ResourceManager.GetString("46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File save environment error.
        /// </summary>
        public static string _47 {
            get {
                return ResourceManager.GetString("47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No write privileges to the file.
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is not specified.
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more documents left.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path is invalid.
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No write privileges to the specified
        ///directory.
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not the NegotiateCapabilities
        ///event. Call the GetCapability or SetCapability
        ///method using the NegotiateCapabilities
        ///event..
        /// </summary>
        public static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter specified for the
        ///GetCapability method is invalid.
        /// </summary>
        public static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected paper multi-feed or
        ///double-feed).
        /// </summary>
        public static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomaly in IPC option.
        /// </summary>
        public static string _55 {
            get {
                return ResourceManager.GetString("55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADF setup error, roller may be attached incorrectly.
        /// </summary>
        public static string _56 {
            get {
                return ResourceManager.GetString("56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprinter (Endorser) print area
        ///specification error.
        /// </summary>
        public static string _57 {
            get {
                return ResourceManager.GetString("57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Imprinter (Endorser) ink
        ///cartridge.
        /// </summary>
        public static string _58 {
            get {
                return ResourceManager.GetString("58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeederLoaded method is not
        ///supported, twain driver may be old.
        /// </summary>
        public static string _59 {
            get {
                return ResourceManager.GetString("59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor fuse for FB is blown.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal skew detected, document is slanted.
        /// </summary>
        public static string _61 {
            get {
                return ResourceManager.GetString("61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in specified scan area, scan area or document size invalid.
        /// </summary>
        public static string _62 {
            get {
                return ResourceManager.GetString("62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed mode switching detected, check feed mode switch.
        /// </summary>
        public static string _68 {
            get {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents are detected in both
        ///the ADF paper chute and the Return
        ///path opening.
        ///Or, a paper jam has occurred.
        /// </summary>
        public static string _69 {
            get {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor fuse for ADF is blown.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuse for heater is blown.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuse for lamp is blown.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System environment error, restart computer and scanner. If error persists contact Ricoh support.
        /// </summary>
        public static string _98 {
            get {
                return ResourceManager.GetString("98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, restart scanner and computer, if error persists contact Ricoh support.
        /// </summary>
        public static string _99 {
            get {
                return ResourceManager.GetString("99", resourceCulture);
            }
        }
    }
}
